# Generated by Django 5.2.7 on 2025-10-01 17:59

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("config", models.JSONField(blank=True, default=dict)),
                ("messages", models.JSONField(blank=True, default=list)),
                ("file_data", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_activity", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-last_activity"],
                "indexes": [
                    models.Index(
                        fields=["-last_activity"], name="chat_sessio_last_ac_585960_idx"
                    )
                ],
            },
        ),
    ]
