# Generated by Django 5.2.6 on 2025-10-11 12:20

import uuid

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Collection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("is_public", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "kb_collections",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("file_type", models.CharField(max_length=50)),
                ("file_path", models.CharField(max_length=1000)),
                ("file_size", models.BigIntegerField()),
                ("content", models.TextField()),
                ("metadata", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("source_url", models.URLField(blank=True)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("upload", "Upload"),
                            ("confluence", "Confluence"),
                            ("notion", "Notion"),
                            ("sharepoint", "SharePoint"),
                            ("web", "Web Scrape"),
                        ],
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "kb_documents",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DocumentChunk",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("content", models.TextField()),
                ("chunk_index", models.IntegerField()),
                ("embedding", pgvector.django.vector.VectorField(dimensions=1536)),
                ("tokens", models.IntegerField()),
                ("metadata", models.JSONField(default=dict)),
            ],
            options={
                "db_table": "kb_chunks",
                "ordering": ["document", "chunk_index"],
            },
        ),
    ]
