# Generated by Django 5.2.6 on 2025-10-11 12:32

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AIModel",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("provider", models.CharField(max_length=50)),
                ("model_id", models.CharField(max_length=100, unique=True)),
                ("display_name", models.CharField(max_length=100)),
                ("supports_vision", models.BooleanField(default=False)),
                ("supports_function_calling", models.BooleanField(default=False)),
                ("max_context_tokens", models.IntegerField()),
                ("max_output_tokens", models.IntegerField()),
                ("input_price", models.DecimalField(decimal_places=4, max_digits=10)),
                ("output_price", models.DecimalField(decimal_places=4, max_digits=10)),
                ("is_available", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "ai_models",
                "ordering": ["provider", "model_id"],
            },
        ),
        migrations.CreateModel(
            name="Assistant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("display_name", models.CharField(max_length=255)),
                ("icon_url", models.URLField(blank=True)),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("claude", "Anthropic Claude"),
                            ("openai", "OpenAI GPT"),
                            ("gemini", "Google Gemini"),
                        ],
                        max_length=50,
                    ),
                ),
                ("model", models.CharField(max_length=100)),
                (
                    "system_instructions",
                    models.TextField(help_text="System prompt for the assistant"),
                ),
                ("temperature", models.FloatField(default=0.7)),
                ("max_tokens", models.IntegerField(default=2000)),
                ("supports_vision", models.BooleanField(default=False)),
                ("supports_function_calling", models.BooleanField(default=False)),
                ("supports_file_analysis", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_default", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "assistants",
                "ordering": ["name"],
            },
        ),
    ]
