# Generated by Django 5.2.6 on 2025-10-11 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("assistants", "0001_initial"),
        ("knowledge_base", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="assistant",
            name="knowledge_collections",
            field=models.ManyToManyField(
                blank=True, related_name="assistants", to="knowledge_base.collection"
            ),
        ),
    ]
