# Generated by Django 5.2.6 on 2025-10-11 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("assistants", "0002_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="assistant",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assistants",
                to="users.organization",
            ),
        ),
        migrations.AddIndex(
            model_name="assistant",
            index=models.Index(
                fields=["organization", "is_active"],
                name="assistants_organiz_63abe5_idx",
            ),
        ),
    ]
