# Generated by Django 5.2.6 on 2025-10-08 09:11

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("config", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_activity", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="clients.client",
                    ),
                ),
            ],
            options={
                "db_table": "chatbot_sessions_session",
                "ordering": ["-last_activity"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("user", "User"),
                            ("assistant", "Assistant"),
                            ("system", "System"),
                        ],
                        max_length=20,
                    ),
                ),
                ("content", models.TextField()),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversation_messages",
                        to="chat.session",
                    ),
                ),
            ],
            options={
                "db_table": "conversation_messages",
                "ordering": ["timestamp"],
            },
        ),
        migrations.CreateModel(
            name="FileUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_name", models.CharField(max_length=255)),
                ("file_path", models.CharField(max_length=500)),
                (
                    "file_type",
                    models.CharField(
                        choices=[("json", "JSON"), ("csv", "CSV")], max_length=10
                    ),
                ),
                ("file_size", models.IntegerField(help_text="File size in bytes")),
                (
                    "processed_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Parsed and processed file data",
                    ),
                ),
                (
                    "summary",
                    models.TextField(
                        blank=True, help_text="AI-generated summary of file"
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="False if file has been deleted"
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uploaded_files",
                        to="chat.session",
                    ),
                ),
            ],
            options={
                "db_table": "file_uploads",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.AddIndex(
            model_name="session",
            index=models.Index(
                fields=["-last_activity"], name="chatbot_ses_last_ac_51af55_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["session", "timestamp"], name="conversatio_session_c9e0af_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["session", "-timestamp"], name="conversatio_session_a27a84_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fileupload",
            index=models.Index(
                fields=["session", "-uploaded_at"],
                name="file_upload_session_83fd7f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="fileupload",
            index=models.Index(
                fields=["session", "is_active"], name="file_upload_session_3753b7_idx"
            ),
        ),
    ]
