# Generated by Django 5.2.6 on 2025-10-11 12:32

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("assistants", "0001_initial"),
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FileUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_name", models.CharField(max_length=255)),
                ("file_path", models.CharField(max_length=500)),
                (
                    "file_type",
                    models.CharField(
                        choices=[("json", "JSON"), ("csv", "CSV")], max_length=10
                    ),
                ),
                ("file_size", models.IntegerField(help_text="File size in bytes")),
                (
                    "processed_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Parsed and processed file data",
                    ),
                ),
                (
                    "summary",
                    models.TextField(
                        blank=True, help_text="AI-generated summary of file"
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="False if file has been deleted"
                    ),
                ),
            ],
            options={
                "db_table": "file_uploads",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("user", "User"),
                            ("assistant", "Assistant"),
                            ("system", "System"),
                        ],
                        max_length=20,
                    ),
                ),
                ("content", models.TextField()),
                ("is_edited", models.BooleanField(default=False)),
                ("original_content", models.TextField(blank=True)),
                ("edited_at", models.DateTimeField(blank=True, null=True)),
                ("provider_name", models.CharField(blank=True, max_length=50)),
                ("model", models.CharField(blank=True, max_length=100)),
                ("prompt_tokens", models.IntegerField(default=0)),
                ("completion_tokens", models.IntegerField(default=0)),
                ("total_tokens", models.IntegerField(default=0)),
                (
                    "cost",
                    models.DecimalField(decimal_places=6, default=0, max_digits=10),
                ),
                ("attachments", models.JSONField(blank=True, default=list)),
                (
                    "kb_sources",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Knowledge base sources used for generating this response",
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "db_table": "conversation_messages",
                "ordering": ["timestamp"],
            },
        ),
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                ("tags", models.JSONField(blank=True, default=list)),
                (
                    "user_identifier",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                ("config", models.JSONField(blank=True, default=dict)),
                ("archived", models.BooleanField(default=False)),
                ("is_shared", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_activity", models.DateTimeField(auto_now=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("total_tokens", models.IntegerField(default=0)),
                (
                    "total_cost",
                    models.DecimalField(decimal_places=4, default=0, max_digits=10),
                ),
                ("message_count", models.IntegerField(default=0)),
                (
                    "assistant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="assistants.assistant",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="clients.client",
                    ),
                ),
            ],
            options={
                "db_table": "chatbot_sessions_session",
                "ordering": ["-last_activity"],
            },
        ),
    ]
