# Generated by Django 5.2.6 on 2025-10-11 12:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("chat", "0001_initial"),
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_sessions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="session",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sessions",
                to="users.organization",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="conversation_messages",
                to="chat.session",
            ),
        ),
        migrations.AddField(
            model_name="fileupload",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="uploaded_files",
                to="chat.session",
            ),
        ),
        migrations.AddIndex(
            model_name="session",
            index=models.Index(
                fields=["-last_activity"], name="chatbot_ses_last_ac_51af55_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="session",
            index=models.Index(
                fields=["organization", "-last_activity"],
                name="chatbot_ses_organiz_b65f05_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="session",
            index=models.Index(
                fields=["created_by", "-created_at"],
                name="chatbot_ses_created_433112_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="session",
            index=models.Index(
                fields=["archived", "-last_activity"],
                name="chatbot_ses_archive_73c48a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["session", "timestamp"], name="conversatio_session_c9e0af_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["session", "-timestamp"], name="conversatio_session_a27a84_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["session", "role"], name="conversatio_session_5348e5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fileupload",
            index=models.Index(
                fields=["session", "-uploaded_at"],
                name="file_upload_session_83fd7f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="fileupload",
            index=models.Index(
                fields=["session", "is_active"], name="file_upload_session_3753b7_idx"
            ),
        ),
    ]
