# Generated by Django 5.2.6 on 2026-02-27 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_session_user_identifier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="role",
            field=models.CharField(
                choices=[
                    ("user", "User"),
                    ("assistant", "Assistant"),
                    ("system", "System"),
                    ("tool", "Tool"),
                ],
                max_length=20,
            ),
        ),
    ]
