# Generated by Django 5.2.6 on 2025-10-06 03:24

import os

from django.db import migrations


def create_default_client(apps, schema_editor):
    """Create a default client for backward compatibility"""
    Client = apps.get_model("clients", "Client")
    Session = apps.get_model("chat_sessions", "Session")

    # Create default client with environment-based configuration
    default_client, created = Client.objects.get_or_create(
        email="system@default.local",
        defaults={
            "name": os.getenv("BOT_NAME", "System Client"),
            "config": {
                "bot_name": os.getenv("BOT_NAME", "AI Assistant"),
                "primary_color": os.getenv("BOT_COLOR", "#667eea"),
                "bot_message_bg_color": os.getenv("BOT_MSG_BG_COLOR", "#667eea"),
                "bot_icon_url": os.getenv("BOT_ICON"),
                "powered_by_text": os.getenv("BOT_POWERED_BY", "Powered by AI"),
                "whitelisted_domains": [
                    "*"
                ],  # Allow all domains for backward compatibility
            },
        },
    )

    if created:
        print(f"\nCreated default client: {default_client.name}")
        print(f"API Key: {default_client.api_key}\n")
        print("IMPORTANT: Save this API key! It will be needed for API requests.\n")

    # Link all existing sessions without a client to the default client
    sessions_updated = Session.objects.filter(client__isnull=True).update(
        client=default_client
    )

    if sessions_updated > 0:
        print(f"Linked {sessions_updated} existing session(s) to default client")


def reverse_migration(apps, schema_editor):
    """Remove default client"""
    Client = apps.get_model("clients", "Client")
    Client.objects.filter(email="system@default.local").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0001_initial"),
        ("chat_sessions", "0002_session_client"),
    ]

    operations = [
        migrations.RunPython(create_default_client, reverse_migration),
    ]
