# Generated by Django 5.2.7 on 2026-04-19 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="api_key",
            field=models.CharField(
                db_index=True, editable=False, max_length=80, unique=True
            ),
        ),
    ]
