# Generated by Django 5.2.6 on 2025-10-11 12:32

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PromptTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("category", models.CharField(max_length=100)),
                (
                    "template",
                    models.TextField(help_text="Prompt with {{variable}} placeholders"),
                ),
                (
                    "variables",
                    models.JSONField(
                        default=list,
                        help_text="List of variable names and descriptions",
                    ),
                ),
                ("is_public", models.BooleanField(default=False)),
                ("use_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "prompt_templates",
                "ordering": ["name"],
            },
        ),
    ]
