"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent

# Initialize environment variables
env = environ.Env(
    DEBUG=(bool, False),
    ALLOWED_HOSTS=(list, []),
)
environ.Env.read_env(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env(
    "SECRET_KEY",
    default="django-insecure-1z954b8y128oob-@1idnwae9d_l^j6m6ge6x^%)!jrpl1xil9u",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env("DEBUG", default=True)

ALLOWED_HOSTS = env("ALLOWED_HOSTS", default=["*"])


# Application definition

DJANGO_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

THIRD_PARTY_APPS = [
    "rest_framework",
    "corsheaders",
]

LOCAL_APPS = [
    "core",
    "ai_providers",
    "clients",
    "chat",
]

INSTALLED_APPS = DJANGO_APPS + THIRD_PARTY_APPS + LOCAL_APPS

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    # XFrameOptionsMiddleware removed - using DomainWhitelistMiddleware for access control
    "core.middleware.DomainWhitelistMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates", BASE_DIR / "static"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [BASE_DIR / "static"]

# Media files (uploads)
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# CORS Configuration
CORS_ALLOWED_ORIGINS = (
    env("ALLOWED_ORIGINS", default="http://localhost:3000").split(",")
    if env("ALLOWED_ORIGINS", default="*") != "*"
    else []
)
CORS_ALLOW_ALL_ORIGINS = env("ALLOWED_ORIGINS", default="*") == "*" or "*" in env(
    "ALLOWED_ORIGINS", default=""
).split(",")
CORS_ALLOW_CREDENTIALS = True

# Django REST Framework
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "core.authentication.APIKeyAuthentication",
    ],
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
        "rest_framework.renderers.BrowsableAPIRenderer",
    ],
    "DEFAULT_PARSER_CLASSES": [
        "rest_framework.parsers.JSONParser",
        "rest_framework.parsers.MultiPartParser",
        "rest_framework.parsers.FormParser",
    ],
}

# CSRF Configuration for API
CSRF_TRUSTED_ORIGINS = (
    env("ALLOWED_ORIGINS", default="http://localhost:3000").split(",")
    if env("ALLOWED_ORIGINS", default="*") != "*"
    else []
)

# AI Provider Configuration
ANTHROPIC_API_KEY = env("ANTHROPIC_API_KEY", default=None)
OPENAI_API_KEY = env("OPENAI_API_KEY", default=None)
AI_PROVIDER = env("AI_PROVIDER", default="claude")
ENABLE_DUMMY_PROVIDER = env("ENABLE_DUMMY_PROVIDER", default=False)

# Model Configuration
CLAUDE_MODEL = env("CLAUDE_MODEL", default="claude-3-5-haiku-20241022")
OPENAI_MODEL = env("OPENAI_MODEL", default="gpt-4o")
DUMMY_MODEL = env("DUMMY_MODEL", default="dummy-1.0")

# Bot Configuration
BOT_NAME = env("BOT_NAME", default="ChatBot Assistant")
BOT_POWERED_BY = env("BOT_POWERED_BY", default="ChatBot")
BOT_COLOR = env("BOT_COLOR", default="#667eea")
BOT_MSG_BG_COLOR = env("BOT_MSG_BG_COLOR", default="#667eea")
BOT_ICON = env("BOT_ICON", default=None)
CLAUDE_BOT_NAME = env("CLAUDE_BOT_NAME", default="ChatBot Assistant")
OPENAI_BOT_NAME = env("OPENAI_BOT_NAME", default="ChatBot Assistant")
DUMMY_BOT_NAME = env("DUMMY_BOT_NAME", default="ChatBot Assistant")

# Widget Configuration
WIDGET_BASE_URL = env("WIDGET_BASE_URL", default="http://localhost:8000")

# Session Configuration
CHAT_SESSION_TIMEOUT = 30 * 60  # 30 minutes in seconds

# File Upload Configuration
FILE_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10MB
